# ~/.config/starship.toml

# Insere uma linha em branco entre os prompts
add_newline = true

# Define a paleta de cores a ser usada
palette = "catppuccin_mocha"

# Define a ordem e o formato do prompt
format = """
[](palette:surface2)\
$os\
$username\
[](bg:palette:blue fg:palette:surface2)\
$directory\
[](fg:palette:peach bg:palette:surface0)\
$git_branch\
$git_status\
[](fg:palette:peach bg:palette:surface0)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:palette:surface0 bg:palette:surface0)\
$line_break\
[ ](fg:palette:surface0)\
$character"""

# Define as paletas de cores do Catppuccin
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1f2e"
mantle = "#181825"
crust = "#11111b"
